Added optional eventEmitter for auto tokens refresh
DaoCasino/game-js-sdk pull request #12
Opened 2020-06-10 08:56 UTC by SCaptainCAP

2020-06-10 08:58 UTC, SCaptainCAP commented
Published to NPM as 1.3.4

2020-06-10 10:02 UTC, Garik- requested changes

2020-06-10 10:02 UTC, Garik- commented on package.json
> +    "redux-saga": "^1.1.3"
Не понял зачем SDK resux-saga?

2020-06-10 10:02 UTC, Garik- commented on src/eventEmitter.ts
> +export class EventEmitter {
Для полноты картины не хватает off и once

2020-06-15 09:16 UTC, Garik- commented on src/eventEmitter.ts
> +        if (this.subscribers[eventName] == undefined) return this;
if (eventName in this.subscribers) так корректнее имхо

2020-06-15 09:18 UTC, Garik- commented on src/eventEmitter.ts
> +        if (this.subscribers[eventName] == undefined) return this;
if (eventName in this.subscribers) так корректнее имхо

2020-06-15 09:18 UTC, Garik- approved these changes

2020-06-15 09:31 UTC, merged